# Generated by Django 5.2.4 on 2025-07-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="paid_course",
            new_name="course",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="paid_lesson",
            new_name="lessons",
        ),
    ]
