# Generated by Django 5.2.4 on 2025-08-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_paid_course_payments_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
