# Generated by Django 5.2.4 on 2025-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payments_link_payments_session_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payments",
            name="link",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="session_id",
        ),
        migrations.AddField(
            model_name="payments",
            name="link_course",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="link_lesson",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id_course",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="id сессии"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="session_id_lesson",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="id сессии"
            ),
        ),
    ]
