# Generated by Django 5.2.4 on 2025-08-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_remove_payments_link_remove_payments_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="date",
            field=models.DateField(auto_now=True, verbose_name="дата платежа"),
        ),
    ]
