# Generated by Django 5.2.4 on 2025-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="course_image/",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lessons_image/",
                verbose_name="картинка",
            ),
        ),
        migrations.AlterField(
            model_name="lessons",
            name="video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="ссылка на видео"
            ),
        ),
    ]
